# Generated by Django 4.2.4 on 2023-09-12 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_no', models.IntegerField()),
                ('engine_no', models.IntegerField()),
                ('chassis_no', models.IntegerField()),
                ('Fuel', models.CharField(max_length=10)),
                ('Fuel_cap', models.IntegerField()),
                ('Manufacturer', models.CharField(max_length=100)),
                ('Model', models.CharField(max_length=200)),
                ('RC', models.DateField()),
                ('Insurance', models.DateField()),
            ],
        ),
    ]
