# Generated by Django 4.2.4 on 2023-09-13 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminDashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.IntegerField()),
                ('hardware_ver', models.CharField(max_length=200)),
                ('software_ver', models.CharField(max_length=200)),
                ('model', models.CharField(max_length=200)),
            ],
        ),
    ]
