# Generated by Django 4.2.4 on 2023-09-13 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminDashboard', '0002_device'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('blood_group', models.CharField(max_length=10)),
                ('licence_no', models.CharField(max_length=100)),
            ],
        ),
    ]
