# Generated by Django 4.2.4 on 2023-09-22 13:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adminDashboard', '0003_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('deviceId', models.ManyToManyField(to='adminDashboard.device')),
                ('personId', models.ManyToManyField(to='adminDashboard.person')),
                ('userId', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('vheicleId', models.ManyToManyField(to='adminDashboard.vehicle')),
            ],
        ),
    ]
